[environments.dev]
store = "hike-your-mind-6en7jqe1.myshopify.com"

[environments.staging]
store = "hike-your-mind-6en7jqe1.myshopify.com"
theme = "198562972031"

[environments.production]
store = "hike-your-mind-6en7jqe1.myshopify.com"
theme = "198563004799"
